site_name: wither
site_description: An API that returns the min, max, average and median temperature and humidity for given city and period of time.
repo_url: https://github.com/crintus/wither
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/crintus">crintus</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
